# This is a basic workflow that is manually triggered

name: Publish to Nuget

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $PWD/Src
    - name: Build Release
      run: dotnet build $PWD/Src -c Release --no-restore
    - name: Push Signed to NuGet
      run: |
        dotnet pack /Src/Serilog.Sinks.AzureDataExplorer/ -c Release -o $PWD/Release/nuget
        for file in Release/nuget/*.nupkg; do dotnet nuget push -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} $file; done
